#!/bin/sh
#
# {LNCPMV,"{cp,mv}{date,note,time,orig} {args}"}
#
# If called as LNCPMV, creates the files listed in LIST below as hardlinks.
#
# +  Original cpdate:  "jsloan@wright, 10Dec1986"
# +  {cp,mv}note:  pedwards@cs.wright.edu  11Nov1994
# +  mvdate:  pedwards@cs.wright.edu  19Nov95
# +  Copied to AAMR on W-P AFB, pedwards 22Oct97
# +  Merged into one script, date changed from 'ddmmmyy' to
#    extended ISO8601 format, added LNCPMV.  pedwards 6Dec1999
# +  *time:  added especially for rotlog.  Yes, that 'T' is supposed
#    to be there as per 8601.  pedwards 8Dec1999
#
#####################################################################

# Todo:
# - Add rs* function , to restore files from foo.bak to foo
#   Complicated, because it involves rewriting
#   the $cmd $source $target segment
# - Add ability to move directories as well


DATE=/bin/date
LIST='cpdate cpnote cptime cpbak cporig mvdate mvnote mvtime mvbak mvorig'
PATH=/bin:$PATH

## No more changes should be needed, unless new names are being added.
#####################################################################

key=$(basename $0)

case $key in
  cp*)  cmd='/bin/cp -p';;
  mv*)  cmd='/bin/mv'   ;;
  LNCPMV)  for i in $LIST; do
    [ -f $i ] && rm $i
      ln -v "$0" $i
    done;
    exit 0 ;;
  *)    echo "$0 unmatched -- what command is that"; exit 1 ;;
esac

case $key in
  *date)
  case $# in
    1) source="$1"; target="$1" ;;
    2) source="$1"; target="${2}/${1}" ;;
    *) echo "Usage:   $key file [path]"; exit 1 ;;
  esac

  target="${target}.$($DATE '+%Y-%m-%d').bak"
  ;;
  *time)
  case $# in
    1) source="$1"; target="$1" ;;
    2) source="$1"; target="${2}/${1}" ;;
    *) echo "Usage:   $key file [path]"; exit 1 ;;
  esac

  target="${target}.$($DATE '+%Y-%m-%dT%T').bak"
  ;;
  *bak)
  case $# in
    1) source="$1"; target="$1.bak" ;;
    2) source="$1"; target="${2}/${1}.bak" ;;
    *) echo "Usage:   $key file [path]"; exit 1 ;;
  esac
  ;;
  *orig)
  case $# in
    1) source="$1"; target="$1.orig" ;;
    2) source="$1"; target="${2}/${1}.orig" ;;
    *) echo "Usage:   $key file [path]"; exit 1 ;;
  esac
  ;;
  *note)
  case $# in
    2) source="$1"; target="${1}.${2}" ;;
    3) source="$1"; target="${2}/${1}.${3}" ;;
    *) echo "Usage:   $key file [path] note"; exit 1 ;;
  esac
  ;;
esac

echo $cmd "$source" "$target"
$cmd "$source" "$target"
